### ISSUE TITLE
OBS web-socket should be removable from any positiion

### ISSUE THREAD

**Issue by iAnanich** [Infernion/obs-multilang-control#2]

**Comment by eirenik0** [comment]
Not sure that I follow this issue. Could you describe what do you mean?

**Comment by iAnanich** [comment]
At this moment, OBS connections tab does not allow you to remove any
connection listed - only the last one. And what I'm proposing is that user
should be able tp remove any connection from the list, or change them.
Settings integrity during usage period could be guaranteed by "lock" button.

**Comment by eirenik0** [comment]
https://github.com/Infernion/obs-multilang-control/pull/3
